name: 'dbt_utils'
version: '0.7.0'

require-dbt-version: [">=0.20.0", "<1.1.0"]

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"
