version: 2

models:
  - name: test_urls
    data_tests:
      - assert_equal:
          actual: actual
          expected: expected
          
  - name: test_url_host
    data_tests:
      - assert_equal:
          actual: actual
          expected: expected
          
  - name: test_url_path
    data_tests:
      - assert_equal:
          actual: actual
          expected: expected