
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch
      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout

      - run:
          run: setup_creds
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Run Tests - Postgres"
          environment:
            CI_DBT_HOST: localhost
            CI_DBT_USER: root
            CI_DBT_PASS: ''
            CI_DBT_PORT: 5432
            CI_DBT_DBNAME: circle_test
          command: ./run_test.sh postgres

      - run:
          name: "Run Tests - Redshift"
          command: ./run_test.sh redshift

      - run:
          name: "Run Tests - Snowflake"
          command: ./run_test.sh snowflake

      - run:
          name: "Run Tests - BigQuery"
          environment:
              GCLOUD_SERVICE_KEY_PATH: "/home/circleci/gcloud-service-key.json"
          command: ./run_test.sh bigquery

      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
