version: 2

models:
  - name: data_test_not_constant
    columns:
      - name: field
        tests:
          - dbt_utils.not_constant
      
  - name: data_test_at_least_one
    columns:
      - name: field
        tests:
          - dbt_utils.at_least_one
      
  - name: test_recency
    tests:
      - dbt_utils.recency:
          datepart: day
          field: today
          interval: 1
        
  - name: data_people
    columns:
      - name: is_active
        tests:
          - dbt_utils.cardinality_equality:
              field: is_active
              to: ref('data_people')