version: 2

models:
  - name: data_test_not_constant
    columns:
      - name: field
        tests:
          - dbt_utils.not_constant
      
  - name: data_test_at_least_one
    columns:
      - name: field
        tests:
          - dbt_utils.at_least_one
      
  - name: data_test_expression_is_true
    tests:
      - dbt_utils.expression_is_true:
          expression: col_a + col_b = 1
        
  - name: test_recency
    tests:
      - dbt_utils.recency:
          datepart: day
          field: today
          interval: 1

  - name: test_equal_expression
    tests:
      - dbt_utils.equal_expression:
          expression: count(*)
          compare_model: ref('test_equal_expression')
      - dbt_utils.equal_expression:
          expression: count(*)
          compare_model: ref('test_equal_expression')
          group_by: [date_col]
      - dbt_utils.equal_expression:
          expression: sum(col_a)
          compare_model: ref('test_equal_expression')
      - dbt_utils.equal_expression:
          expression: sum(col_a)
          compare_expression: sum(col_b)
          group_by: [date_col]
      - dbt_utils.equal_expression:
          expression: sum(col_a)
          compare_expression: sum(col_b)
          compare_model: ref('test_equal_expression')
          group_by: [date_col]
          tol: 0.1
      - dbt_utils.equal_expression:
          expression: sum(col_b)
          compare_model: ref('test_equal_expression')
          group_by: [date_col, col_a]

  - name: data_people
    columns:
      - name: is_active
        tests:
          - dbt_utils.cardinality_equality:
              field: is_active
              to: ref('data_people')