version: 2

models:
  - name: test_haversine_distance_km
    data_tests:
      - assert_equal:
          actual: actual
          expected: expected
  - name: test_haversine_distance_mi
    data_tests:
      - assert_equal:
          actual: actual
          expected: expected
